# Generated by Django 5.2.7 on 2025-10-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "water_type",
                    models.CharField(
                        choices=[
                            ("borehole", "Borehole"),
                            ("well", "Well"),
                            ("river", "River"),
                            ("lake", "Lake"),
                            ("dam", "Dam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "nearest_village",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "capacity_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("condition", models.CharField(default="Unknown", max_length=100)),
                ("image", models.URLField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
